version: 2
updates:
  - package-ecosystem: github-actions
    directory: .github/workflows
    schedule:
      interval: daily
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
